import tkinter as tk
from tkinter import ttk
from tkinter.messagebox import showerror
from math import pi


def convert(x):
    if cbox1_var.get() == "mm" and cbox2_var.get() == "mm": result.set(entryvar.get())
    elif cbox1_var.get() == "mm" and cbox2_var.get() == "cm": result.set(entryvar.get()/10)
    elif cbox1_var.get() == "mm" and cbox2_var.get() == "m": result.set(entryvar.get()/100)
    elif cbox1_var.get() == "mm" and cbox2_var.get() == "km": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "mm" and cbox2_var.get() == "in": result.set(entryvar.get()/25.4)
    elif cbox1_var.get() == "mm" and cbox2_var.get() == "ft": result.set(entryvar.get()/304.8)
    elif cbox1_var.get() == "mm" and cbox2_var.get() == "mi": result.set(entryvar.get()/1609000)
    elif cbox1_var.get() == "mm" and cbox2_var.get() == "ly": result.set(entryvar.get()/9.461e+18)
    elif cbox1_var.get() == "cm" and cbox2_var.get() == "mm": result.set(entryvar.get()*10)
    elif cbox1_var.get() == "cm" and cbox2_var.get() == "cm": result.set(entryvar.get())
    elif cbox1_var.get() == "cm" and cbox2_var.get() == "m": result.set(entryvar.get()/10)
    elif cbox1_var.get() == "cm" and cbox2_var.get() == "km": result.set(entryvar.get()/100)
    elif cbox1_var.get() == "cm" and cbox2_var.get() == "in": result.set(entryvar.get()/2.54)
    elif cbox1_var.get() == "cm" and cbox2_var.get() == "ft": result.set(entryvar.get()/30.48)
    elif cbox1_var.get() == "cm" and cbox2_var.get() == "mi": result.set(entryvar.get()/160900)
    elif cbox1_var.get() == "cm" and cbox2_var.get() == "ly": result.set(entryvar.get()/9.461e+17)
    elif cbox1_var.get() == "m" and cbox2_var.get() == "mm": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "m" and cbox2_var.get() == "cm": result.set(entryvar.get()*100)
    elif cbox1_var.get() == "m" and cbox2_var.get() == "m": result.set(entryvar.get())
    elif cbox1_var.get() == "m" and cbox2_var.get() == "km": result.set(entryvar.get()/10)
    elif cbox1_var.get() == "m" and cbox2_var.get() == "in": result.set(entryvar.get()*39.37)
    elif cbox1_var.get() == "m" and cbox2_var.get() == "ft": result.set(entryvar.get()*3.281)
    elif cbox1_var.get() == "m" and cbox2_var.get() == "mi": result.set(entryvar.get()*1609)
    elif cbox1_var.get() == "m" and cbox2_var.get() == "ly": result.set(entryvar.get()/9.461e+15)
    elif cbox1_var.get() == "km" and cbox2_var.get() == "mm": result.set(entryvar.get()*1000000)
    elif cbox1_var.get() == "km" and cbox2_var.get() == "cm": result.set(entryvar.get()*100000)
    elif cbox1_var.get() == "km" and cbox2_var.get() == "m": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "km" and cbox2_var.get() == "km": result.set(entryvar.get())
    elif cbox1_var.get() == "km" and cbox2_var.get() == "in": result.set(entryvar.get()*39370)
    elif cbox1_var.get() == "km" and cbox2_var.get() == "ft": result.set(entryvar.get()*3281)
    elif cbox1_var.get() == "km" and cbox2_var.get() == "mi": result.set(entryvar.get()*1.609)
    elif cbox1_var.get() == "km" and cbox2_var.get() == "ly": result.set(entryvar.get()/9.461e+12)
    elif cbox1_var.get() == "in" and cbox2_var.get() == "mm": result.set(entryvar.get()*25.4)
    elif cbox1_var.get() == "in" and cbox2_var.get() == "cm": result.set(entryvar.get()*2.54)
    elif cbox1_var.get() == "in" and cbox2_var.get() == "m": result.set(entryvar.get()/39.37)
    elif cbox1_var.get() == "in" and cbox2_var.get() == "km": result.set(entryvar.get()/39370)
    elif cbox1_var.get() == "in" and cbox2_var.get() == "in": result.set(entryvar.get())
    elif cbox1_var.get() == "in" and cbox2_var.get() == "ft": result.set(entryvar.get()/12)
    elif cbox1_var.get() == "in" and cbox2_var.get() == "mi": result.set(entryvar.get()/63360)
    elif cbox1_var.get() == "in" and cbox2_var.get() == "ly": result.set(entryvar.get()/3.725e+17)
    elif cbox1_var.get() == "ft" and cbox2_var.get() == "mm": result.set(entryvar.get()*304.8)
    elif cbox1_var.get() == "ft" and cbox2_var.get() == "cm": result.set(entryvar.get()*30.48)
    elif cbox1_var.get() == "ft" and cbox2_var.get() == "m": result.set(entryvar.get()/3.281)
    elif cbox1_var.get() == "ft" and cbox2_var.get() == "km": result.set(entryvar.get()*3281)
    elif cbox1_var.get() == "ft" and cbox2_var.get() == "in": result.set(entryvar.get()*12)
    elif cbox1_var.get() == "ft" and cbox2_var.get() == "ft": result.set(entryvar.get())
    elif cbox1_var.get() == "ft" and cbox2_var.get() == "mi": result.set(entryvar.get()/5280)
    elif cbox1_var.get() == "ft" and cbox2_var.get() == "ly": result.set(entryvar.get()/3.104e+16)
    elif cbox1_var.get() == "mi" and cbox2_var.get() == "mm": result.set(entryvar.get()*1609000)
    elif cbox1_var.get() == "mi" and cbox2_var.get() == "cm": result.set(entryvar.get()*160900)
    elif cbox1_var.get() == "mi" and cbox2_var.get() == "m": result.set(entryvar.get()*1609)
    elif cbox1_var.get() == "mi" and cbox2_var.get() == "km": result.set(entryvar.get()*1.609)
    elif cbox1_var.get() == "mi" and cbox2_var.get() == "in": result.set(entryvar.get()*63360)
    elif cbox1_var.get() == "mi" and cbox2_var.get() == "ft": result.set(entryvar.get()*5280)
    elif cbox1_var.get() == "mi" and cbox2_var.get() == "mi": result.set(entryvar.get())
    elif cbox1_var.get() == "mi" and cbox2_var.get() == "ly": result.set(entryvar.get()/5.879e+12)
    elif cbox1_var.get() == "ly" and cbox2_var.get() == "mm": result.set(entryvar.get()*9.461e+18)
    elif cbox1_var.get() == "ly" and cbox2_var.get() == "cm": result.set(entryvar.get()*9.461e+17)
    elif cbox1_var.get() == "ly" and cbox2_var.get() == "m": result.set(entryvar.get()*9.461e+15)
    elif cbox1_var.get() == "ly" and cbox2_var.get() == "km": result.set(entryvar.get()*9.461e+12)
    elif cbox1_var.get() == "ly" and cbox2_var.get() == "in": result.set(entryvar.get()*3.725e+17)
    elif cbox1_var.get() == "ly" and cbox2_var.get() == "ft": result.set(entryvar.get()*3.104e+16)
    elif cbox1_var.get() == "ly" and cbox2_var.get() == "mi": result.set(entryvar.get()*5.879e+12)
    elif cbox1_var.get() == "ly" and cbox2_var.get() == "ly": result.set(entryvar.get())
    elif cbox1_var.get() == "cm²" and cbox2_var.get() == "cm²": result.set(entryvar.get())
    elif cbox1_var.get() == "cm²" and cbox2_var.get() == "m²": result.set(entryvar.get()/10000)
    elif cbox1_var.get() == "cm²" and cbox2_var.get() == "km²": result.set(entryvar.get()/10000000000)
    elif cbox1_var.get() == "cm²" and cbox2_var.get() == "are": result.set(entryvar.get()/1000000)
    elif cbox1_var.get() == "cm²" and cbox2_var.get() == "decare": result.set(entryvar.get()/10000000)
    elif cbox1_var.get() == "cm²" and cbox2_var.get() == "hectare": result.set(entryvar.get()/100000000)
    elif cbox1_var.get() == "cm²" and cbox2_var.get() == "sq in": result.set(entryvar.get()/6.452)
    elif cbox1_var.get() == "cm²" and cbox2_var.get() == "sq ft": result.set(entryvar.get()/929)
    elif cbox1_var.get() == "cm²" and cbox2_var.get() == "acre": result.set(entryvar.get()/40470000)
    elif cbox1_var.get() == "m²" and cbox2_var.get() == "cm²": result.set(entryvar.get()*10000)
    elif cbox1_var.get() == "m²" and cbox2_var.get() == "m²": result.set(entryvar.get())
    elif cbox1_var.get() == "m²" and cbox2_var.get() == "km²": result.set(entryvar.get()/1000000)
    elif cbox1_var.get() == "m²" and cbox2_var.get() == "are": result.set(entryvar.get()/100)
    elif cbox1_var.get() == "m²" and cbox2_var.get() == "decare": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "m²" and cbox2_var.get() == "hectare": result.set(entryvar.get()/10000)
    elif cbox1_var.get() == "m²" and cbox2_var.get() == "sq in": result.set(entryvar.get()*1550)
    elif cbox1_var.get() == "m²" and cbox2_var.get() == "sq ft": result.set(entryvar.get()*10.764)
    elif cbox1_var.get() == "m²" and cbox2_var.get() == "acre": result.set(entryvar.get()/4047)
    elif cbox1_var.get() == "km²" and cbox2_var.get() == "cm²": result.set(entryvar.get()*10000000000)
    elif cbox1_var.get() == "km²" and cbox2_var.get() == "m²": result.set(entryvar.get()*1000000)
    elif cbox1_var.get() == "km²" and cbox2_var.get() == "km²": result.set(entryvar.get())
    elif cbox1_var.get() == "km²" and cbox2_var.get() == "are": result.set(entryvar.get()*10000)
    elif cbox1_var.get() == "km²" and cbox2_var.get() == "decare": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "km²" and cbox2_var.get() == "hectare": result.set(entryvar.get()*100)
    elif cbox1_var.get() == "km²" and cbox2_var.get() == "sq in": result.set(entryvar.get()*1550000000)
    elif cbox1_var.get() == "km²" and cbox2_var.get() == "sq ft": result.set(entryvar.get()*10760000)
    elif cbox1_var.get() == "km²" and cbox2_var.get() == "acre": result.set(entryvar.get()*247.1)
    elif cbox1_var.get() == "are" and cbox2_var.get() == "cm²": result.set(entryvar.get()*1000000)
    elif cbox1_var.get() == "are" and cbox2_var.get() == "m²": result.set(entryvar.get()*100)
    elif cbox1_var.get() == "are" and cbox2_var.get() == "km²": result.set(entryvar.get()/10000)
    elif cbox1_var.get() == "are" and cbox2_var.get() == "are": result.set(entryvar.get())
    elif cbox1_var.get() == "are" and cbox2_var.get() == "decare": result.set(entryvar.get()/10)
    elif cbox1_var.get() == "are" and cbox2_var.get() == "hectare": result.set(entryvar.get()/100)
    elif cbox1_var.get() == "are" and cbox2_var.get() == "sq in": result.set(entryvar.get()*155000)
    elif cbox1_var.get() == "are" and cbox2_var.get() == "sq ft": result.set(entryvar.get()*1076)
    elif cbox1_var.get() == "are" and cbox2_var.get() == "acre": result.set(entryvar.get()/40.469)
    elif cbox1_var.get() == "decare" and cbox2_var.get() == "cm²": result.set(entryvar.get()*10000000)
    elif cbox1_var.get() == "decare" and cbox2_var.get() == "m²": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "decare" and cbox2_var.get() == "km²": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "decare" and cbox2_var.get() == "are": result.set(entryvar.get()*10)
    elif cbox1_var.get() == "decare" and cbox2_var.get() == "decare": result.set(entryvar.get())
    elif cbox1_var.get() == "decare" and cbox2_var.get() == "hectare": result.set(entryvar.get()/10)
    elif cbox1_var.get() == "decare" and cbox2_var.get() == "sq in": result.set(entryvar.get()*1550003)
    elif cbox1_var.get() == "decare" and cbox2_var.get() == "sq ft": result.set(entryvar.get()*10764)
    elif cbox1_var.get() == "decare" and cbox2_var.get() == "acre": result.set(entryvar.get()/4.0468)
    elif cbox1_var.get() == "hectare" and cbox2_var.get() == "cm²": result.set(entryvar.get()*100000000)
    elif cbox1_var.get() == "hectare" and cbox2_var.get() == "m²": result.set(entryvar.get()*10000)
    elif cbox1_var.get() == "hectare" and cbox2_var.get() == "km²": result.set(entryvar.get()/100)
    elif cbox1_var.get() == "hectare" and cbox2_var.get() == "are": result.set(entryvar.get()*100)
    elif cbox1_var.get() == "hectare" and cbox2_var.get() == "decare": result.set(entryvar.get()*10)
    elif cbox1_var.get() == "hectare" and cbox2_var.get() == "hectare": result.set(entryvar.get())
    elif cbox1_var.get() == "hectare" and cbox2_var.get() == "sq in": result.set(entryvar.get()*15500000)
    elif cbox1_var.get() == "hectare" and cbox2_var.get() == "sq ft": result.set(entryvar.get()*107600)
    elif cbox1_var.get() == "hectare" and cbox2_var.get() == "acre": result.set(entryvar.get()*2.471)
    elif cbox1_var.get() == "sq in" and cbox2_var.get() == "cm²": result.set(entryvar.get()*6452)
    elif cbox1_var.get() == "sq in" and cbox2_var.get() == "m²": result.set(entryvar.get()/1550)
    elif cbox1_var.get() == "sq in" and cbox2_var.get() == "km²": result.set(entryvar.get()/1550000000)
    elif cbox1_var.get() == "sq in" and cbox2_var.get() == "are": result.set(entryvar.get()/155000)
    elif cbox1_var.get() == "sq in" and cbox2_var.get() == "decare": result.set(entryvar.get()/1550000)
    elif cbox1_var.get() == "sq in" and cbox2_var.get() == "hectare": result.set(entryvar.get()/15500000)
    elif cbox1_var.get() == "sq in" and cbox2_var.get() == "sq in": result.set(entryvar.get())
    elif cbox1_var.get() == "sq in" and cbox2_var.get() == "sq ft": result.set(entryvar.get()/144)
    elif cbox1_var.get() == "sq in" and cbox2_var.get() == "acre": result.set(entryvar.get()/6273000)
    elif cbox1_var.get() == "sq ft" and cbox2_var.get() == "cm²": result.set(entryvar.get()*929)
    elif cbox1_var.get() == "sq ft" and cbox2_var.get() == "m²": result.set(entryvar.get()/10.764)
    elif cbox1_var.get() == "sq ft" and cbox2_var.get() == "km²": result.set(entryvar.get()/10760000)
    elif cbox1_var.get() == "sq ft" and cbox2_var.get() == "are": result.set(entryvar.get()/1076)
    elif cbox1_var.get() == "sq ft" and cbox2_var.get() == "decare": result.set(entryvar.get()/10760)
    elif cbox1_var.get() == "sq ft" and cbox2_var.get() == "hectare": result.set(entryvar.get()/107600)
    elif cbox1_var.get() == "sq ft" and cbox2_var.get() == "sq in": result.set(entryvar.get()*144)
    elif cbox1_var.get() == "sq ft" and cbox2_var.get() == "sq ft": result.set(entryvar.get())
    elif cbox1_var.get() == "sq ft" and cbox2_var.get() == "acre": result.set(entryvar.get()/43560)
    elif cbox1_var.get() == "acre" and cbox2_var.get() == "cm²": result.set(entryvar.get()*40470000)
    elif cbox1_var.get() == "acre" and cbox2_var.get() == "m²": result.set(entryvar.get()*4047)
    elif cbox1_var.get() == "acre" and cbox2_var.get() == "km²": result.set(entryvar.get()/247.1)
    elif cbox1_var.get() == "acre" and cbox2_var.get() == "are": result.set(entryvar.get()*40.469)
    elif cbox1_var.get() == "acre" and cbox2_var.get() == "decare": result.set(entryvar.get()*4.0469)
    elif cbox1_var.get() == "acre" and cbox2_var.get() == "hectare": result.set(entryvar.get()/2.471)
    elif cbox1_var.get() == "acre" and cbox2_var.get() == "sq in": result.set(entryvar.get()*6273000)
    elif cbox1_var.get() == "acre" and cbox2_var.get() == "sq ft": result.set(entryvar.get()*43560)
    elif cbox1_var.get() == "acre" and cbox2_var.get() == "acre": result.set(entryvar.get())
    elif cbox1_var.get() == "cm³" and cbox2_var.get() == "cm³": result.set(entryvar.get())
    elif cbox1_var.get() == "cm³" and cbox2_var.get() == "dm³": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "cm³" and cbox2_var.get() == "m³": result.set(entryvar.get()/1000000)
    elif cbox1_var.get() == "cm³" and cbox2_var.get() == "mL": result.set(entryvar.get())
    elif cbox1_var.get() == "cm³" and cbox2_var.get() == "cL": result.set(entryvar.get()/10)
    elif cbox1_var.get() == "cm³" and cbox2_var.get() == "L": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "cm³" and cbox2_var.get() == "cu in": result.set(entryvar.get()/16.387)
    elif cbox1_var.get() == "cm³" and cbox2_var.get() == "cu ft": result.set(entryvar.get()/28320)
    elif cbox1_var.get() == "dm³" and cbox2_var.get() == "cm³": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "dm³" and cbox2_var.get() == "dm³": result.set(entryvar.get())
    elif cbox1_var.get() == "dm³" and cbox2_var.get() == "m³": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "dm³" and cbox2_var.get() == "mL": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "dm³" and cbox2_var.get() == "cL": result.set(entryvar.get()*100)
    elif cbox1_var.get() == "dm³" and cbox2_var.get() == "L": result.set(entryvar.get())
    elif cbox1_var.get() == "dm³" and cbox2_var.get() == "cu in": result.set(entryvar.get()*61.024)
    elif cbox1_var.get() == "dm³" and cbox2_var.get() == "cu ft": result.set(entryvar.get()/28.317)
    elif cbox1_var.get() == "m³" and cbox2_var.get() == "cm³": result.set(entryvar.get()*1000000)
    elif cbox1_var.get() == "m³" and cbox2_var.get() == "dm³": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "m³" and cbox2_var.get() == "m³": result.set(entryvar.get())
    elif cbox1_var.get() == "m³" and cbox2_var.get() == "mL": result.set(entryvar.get()*1000000)
    elif cbox1_var.get() == "m³" and cbox2_var.get() == "cL": result.set(entryvar.get()*100000)
    elif cbox1_var.get() == "m³" and cbox2_var.get() == "L": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "m³" and cbox2_var.get() == "cu in": result.set(entryvar.get()*61020)
    elif cbox1_var.get() == "m³" and cbox2_var.get() == "cu ft": result.set(entryvar.get()*35.315)
    elif cbox1_var.get() == "mL" and cbox2_var.get() == "cm³": result.set(entryvar.get())
    elif cbox1_var.get() == "mL" and cbox2_var.get() == "dm³": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "mL" and cbox2_var.get() == "m³": result.set(entryvar.get()/1000000)
    elif cbox1_var.get() == "mL" and cbox2_var.get() == "mL": result.set(entryvar.get())
    elif cbox1_var.get() == "mL" and cbox2_var.get() == "cL": result.set(entryvar.get()/10)
    elif cbox1_var.get() == "mL" and cbox2_var.get() == "L": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "mL" and cbox2_var.get() == "cu in": result.set(entryvar.get()/16.387)
    elif cbox1_var.get() == "mL" and cbox2_var.get() == "cu ft": result.set(entryvar.get()/28320)
    elif cbox1_var.get() == "cL" and cbox2_var.get() == "cm³": result.set(entryvar.get()*10)
    elif cbox1_var.get() == "cL" and cbox2_var.get() == "dm³": result.set(entryvar.get()/100)
    elif cbox1_var.get() == "cL" and cbox2_var.get() == "m³": result.set(entryvar.get()/100000)
    elif cbox1_var.get() == "cL" and cbox2_var.get() == "mL": result.set(entryvar.get()*10)
    elif cbox1_var.get() == "cL" and cbox2_var.get() == "cL": result.set(entryvar.get())
    elif cbox1_var.get() == "cL" and cbox2_var.get() == "L": result.set(entryvar.get()/100)
    elif cbox1_var.get() == "cL" and cbox2_var.get() == "cu in": result.set(entryvar.get()/1.639)
    elif cbox1_var.get() == "cL" and cbox2_var.get() == "cu ft": result.set(entryvar.get()/2832)
    elif cbox1_var.get() == "L" and cbox2_var.get() == "cm³": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "L" and cbox2_var.get() == "dm³": result.set(entryvar.get())
    elif cbox1_var.get() == "L" and cbox2_var.get() == "m³": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "L" and cbox2_var.get() == "mL": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "L" and cbox2_var.get() == "cL": result.set(entryvar.get()*100)
    elif cbox1_var.get() == "L" and cbox2_var.get() == "L": result.set(entryvar.get())
    elif cbox1_var.get() == "L" and cbox2_var.get() == "cu in": result.set(entryvar.get()*61.024)
    elif cbox1_var.get() == "L" and cbox2_var.get() == "cu ft": result.set(entryvar.get()/28.317)
    elif cbox1_var.get() == "cu in" and cbox2_var.get() == "cm³": result.set(entryvar.get()*16.387)
    elif cbox1_var.get() == "cu in" and cbox2_var.get() == "dm³": result.set(entryvar.get()/61.024)
    elif cbox1_var.get() == "cu in" and cbox2_var.get() == "m³": result.set(entryvar.get()/61024)
    elif cbox1_var.get() == "cu in" and cbox2_var.get() == "mL": result.set(entryvar.get()*16.387)
    elif cbox1_var.get() == "cu in" and cbox2_var.get() == "cL": result.set(entryvar.get()*1.6387)
    elif cbox1_var.get() == "cu in" and cbox2_var.get() == "L": result.set(entryvar.get()/61.024)
    elif cbox1_var.get() == "cu in" and cbox2_var.get() == "cu in": result.set(entryvar.get())
    elif cbox1_var.get() == "cu in" and cbox2_var.get() == "cu ft": result.set(entryvar.get()/1728)
    elif cbox1_var.get() == "cu ft" and cbox2_var.get() == "cm³": result.set(entryvar.get()*28320)
    elif cbox1_var.get() == "cu ft" and cbox2_var.get() == "dm³": result.set(entryvar.get()*28.32)
    elif cbox1_var.get() == "cu ft" and cbox2_var.get() == "m³": result.set(entryvar.get()/35.315)
    elif cbox1_var.get() == "cu ft" and cbox2_var.get() == "mL": result.set(entryvar.get()*28320)
    elif cbox1_var.get() == "cu ft" and cbox2_var.get() == "cL": result.set(entryvar.get()*2832)
    elif cbox1_var.get() == "cu ft" and cbox2_var.get() == "L": result.set(entryvar.get()*28.32)
    elif cbox1_var.get() == "cu ft" and cbox2_var.get() == "cu in": result.set(entryvar.get()*1728)
    elif cbox1_var.get() == "cu ft" and cbox2_var.get() == "cu ft": result.set(entryvar.get())
    elif cbox1_var.get() == "s" and cbox2_var.get() == "s": result.set(entryvar.get())
    elif cbox1_var.get() == "s" and cbox2_var.get() == "min": result.set(entryvar.get()/60)
    elif cbox1_var.get() == "s" and cbox2_var.get() == "h": result.set(entryvar.get()/3600)
    elif cbox1_var.get() == "s" and cbox2_var.get() == "d": result.set(entryvar.get()/86400)
    elif cbox1_var.get() == "s" and cbox2_var.get() == "wk": result.set(entryvar.get()/604800)
    elif cbox1_var.get() == "s" and cbox2_var.get() == "mo": result.set(entryvar.get()/2628000)
    elif cbox1_var.get() == "s" and cbox2_var.get() == "yr": result.set(entryvar.get()/31540000)
    elif cbox1_var.get() == "min" and cbox2_var.get() == "s": result.set(entryvar.get()*60)
    elif cbox1_var.get() == "min" and cbox2_var.get() == "min": result.set(entryvar.get())
    elif cbox1_var.get() == "min" and cbox2_var.get() == "h": result.set(entryvar.get()/60)
    elif cbox1_var.get() == "min" and cbox2_var.get() == "d": result.set(entryvar.get()/1440)
    elif cbox1_var.get() == "min" and cbox2_var.get() == "wk": result.set(entryvar.get()/10080)
    elif cbox1_var.get() == "min" and cbox2_var.get() == "mo": result.set(entryvar.get()/43800)
    elif cbox1_var.get() == "min" and cbox2_var.get() == "yr": result.set(entryvar.get()/525600)
    elif cbox1_var.get() == "h" and cbox2_var.get() == "s": result.set(entryvar.get()*3600)
    elif cbox1_var.get() == "h" and cbox2_var.get() == "min": result.set(entryvar.get()*60)
    elif cbox1_var.get() == "h" and cbox2_var.get() == "h": result.set(entryvar.get())
    elif cbox1_var.get() == "h" and cbox2_var.get() == "d": result.set(entryvar.get()/24)
    elif cbox1_var.get() == "h" and cbox2_var.get() == "wk": result.set(entryvar.get()/168)
    elif cbox1_var.get() == "h" and cbox2_var.get() == "mo": result.set(entryvar.get()/720)
    elif cbox1_var.get() == "h" and cbox2_var.get() == "yr": result.set(entryvar.get()/8760)
    elif cbox1_var.get() == "d" and cbox2_var.get() == "s": result.set(entryvar.get()*86400)
    elif cbox1_var.get() == "d" and cbox2_var.get() == "min": result.set(entryvar.get()*3600)
    elif cbox1_var.get() == "d" and cbox2_var.get() == "h": result.set(entryvar.get()*24)
    elif cbox1_var.get() == "d" and cbox2_var.get() == "d": result.set(entryvar.get())
    elif cbox1_var.get() == "d" and cbox2_var.get() == "wk": result.set(entryvar.get()/7)
    elif cbox1_var.get() == "d" and cbox2_var.get() == "mo": result.set(entryvar.get()/30)
    elif cbox1_var.get() == "d" and cbox2_var.get() == "yr": result.set(entryvar.get()/365)
    elif cbox1_var.get() == "wk" and cbox2_var.get() == "s": result.set(entryvar.get()*604800)
    elif cbox1_var.get() == "wk" and cbox2_var.get() == "min": result.set(entryvar.get()*10080)
    elif cbox1_var.get() == "wk" and cbox2_var.get() == "h": result.set(entryvar.get()*168)
    elif cbox1_var.get() == "wk" and cbox2_var.get() == "d": result.set(entryvar.get()*7)
    elif cbox1_var.get() == "wk" and cbox2_var.get() == "wk": result.set(entryvar.get())
    elif cbox1_var.get() == "wk" and cbox2_var.get() == "mo": result.set(entryvar.get()/4.345)
    elif cbox1_var.get() == "wk" and cbox2_var.get() == "yr": result.set(entryvar.get()/52.143)
    elif cbox1_var.get() == "mo" and cbox2_var.get() == "s": result.set(entryvar.get()*2628000)
    elif cbox1_var.get() == "mo" and cbox2_var.get() == "min": result.set(entryvar.get()*43800)
    elif cbox1_var.get() == "mo" and cbox2_var.get() == "h": result.set(entryvar.get()*720)
    elif cbox1_var.get() == "mo" and cbox2_var.get() == "d": result.set(entryvar.get()*30)
    elif cbox1_var.get() == "mo" and cbox2_var.get() == "wk": result.set(entryvar.get()*4.345)
    elif cbox1_var.get() == "mo" and cbox2_var.get() == "mo": result.set(entryvar.get())
    elif cbox1_var.get() == "mo" and cbox2_var.get() == "yr": result.set(entryvar.get()/12)
    elif cbox1_var.get() == "yr" and cbox2_var.get() == "s": result.set(entryvar.get()*31540000)
    elif cbox1_var.get() == "yr" and cbox2_var.get() == "min": result.set(entryvar.get()*525600)
    elif cbox1_var.get() == "yr" and cbox2_var.get() == "h": result.set(entryvar.get()*8760)
    elif cbox1_var.get() == "yr" and cbox2_var.get() == "d": result.set(entryvar.get()*365)
    elif cbox1_var.get() == "yr" and cbox2_var.get() == "wk": result.set(entryvar.get()*52.143)
    elif cbox1_var.get() == "yr" and cbox2_var.get() == "mo": result.set(entryvar.get()*12)
    elif cbox1_var.get() == "yr" and cbox2_var.get() == "yr": result.set(entryvar.get())
    elif cbox1_var.get() == "km/h" and cbox2_var.get() == "km/h": result.set(entryvar.get())
    elif cbox1_var.get() == "km/h" and cbox2_var.get() == "m/s": result.set(entryvar.get()/3.6)
    elif cbox1_var.get() == "km/h" and cbox2_var.get() == "mph": result.set(entryvar.get()/1.609)
    elif cbox1_var.get() == "km/h" and cbox2_var.get() == "kn": result.set(entryvar.get()/1.852)
    elif cbox1_var.get() == "km/h" and cbox2_var.get() == "ft/s": result.set(entryvar.get()/1.097)
    elif cbox1_var.get() == "m/s" and cbox2_var.get() == "km/h": result.set(entryvar.get()*3.6)
    elif cbox1_var.get() == "m/s" and cbox2_var.get() == "m/s": result.set(entryvar.get())
    elif cbox1_var.get() == "m/s" and cbox2_var.get() == "mph": result.set(entryvar.get()*2.237)
    elif cbox1_var.get() == "m/s" and cbox2_var.get() == "kn": result.set(entryvar.get()*1.944)
    elif cbox1_var.get() == "m/s" and cbox2_var.get() == "ft/s": result.set(entryvar.get()*3.281)
    elif cbox1_var.get() == "mph" and cbox2_var.get() == "km/h": result.set(entryvar.get()*1.609)
    elif cbox1_var.get() == "mph" and cbox2_var.get() == "m/s": result.set(entryvar.get()/2.237)
    elif cbox1_var.get() == "mph" and cbox2_var.get() == "mph": result.set(entryvar.get())
    elif cbox1_var.get() == "mph" and cbox2_var.get() == "kn": result.set(entryvar.get()/1.151)
    elif cbox1_var.get() == "mph" and cbox2_var.get() == "ft/s": result.set(entryvar.get()*1.467)
    elif cbox1_var.get() == "kn" and cbox2_var.get() == "km/h": result.set(entryvar.get()*1.852)
    elif cbox1_var.get() == "kn" and cbox2_var.get() == "m/s": result.set(entryvar.get()/1.944)
    elif cbox1_var.get() == "kn" and cbox2_var.get() == "mph": result.set(entryvar.get()*1.151)
    elif cbox1_var.get() == "kn" and cbox2_var.get() == "kn": result.set(entryvar.get())
    elif cbox1_var.get() == "kn" and cbox2_var.get() == "ft/s": result.set(entryvar.get()*1.688)
    elif cbox1_var.get() == "ft/s" and cbox2_var.get() == "km/h": result.set(entryvar.get()*1.097)
    elif cbox1_var.get() == "ft/s" and cbox2_var.get() == "m/s": result.set(entryvar.get()/3.281)
    elif cbox1_var.get() == "ft/s" and cbox2_var.get() == "mph": result.set(entryvar.get()/1.467)
    elif cbox1_var.get() == "ft/s" and cbox2_var.get() == "kn": result.set(entryvar.get()/1.688)
    elif cbox1_var.get() == "ft/s" and cbox2_var.get() == "ft/s": result.set(entryvar.get())
    elif cbox1_var.get() == "mg" and cbox2_var.get() == "mg": result.set(entryvar.get())
    elif cbox1_var.get() == "mg" and cbox2_var.get() == "g": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "mg" and cbox2_var.get() == "kg": result.set(entryvar.get()/1000000)
    elif cbox1_var.get() == "mg" and cbox2_var.get() == "t": result.set(entryvar.get()/1000000000)
    elif cbox1_var.get() == "mg" and cbox2_var.get() == "oz": result.set(entryvar.get()/28350)
    elif cbox1_var.get() == "mg" and cbox2_var.get() == "lb": result.set(entryvar.get()/453600)
    elif cbox1_var.get() == "g" and cbox2_var.get() == "mg": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "g" and cbox2_var.get() == "g": result.set(entryvar.get())
    elif cbox1_var.get() == "g" and cbox2_var.get() == "kg": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "g" and cbox2_var.get() == "t": result.set(entryvar.get()/1000000)
    elif cbox1_var.get() == "g" and cbox2_var.get() == "oz": result.set(entryvar.get()/28.35)
    elif cbox1_var.get() == "g" and cbox2_var.get() == "lb": result.set(entryvar.get()/453.6)
    elif cbox1_var.get() == "kg" and cbox2_var.get() == "mg": result.set(entryvar.get()*1000000)
    elif cbox1_var.get() == "kg" and cbox2_var.get() == "g": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "kg" and cbox2_var.get() == "kg": result.set(entryvar.get())
    elif cbox1_var.get() == "kg" and cbox2_var.get() == "t": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "kg" and cbox2_var.get() == "oz": result.set(entryvar.get()*35.274)
    elif cbox1_var.get() == "kg" and cbox2_var.get() == "lb": result.set(entryvar.get()*2.205)
    elif cbox1_var.get() == "t" and cbox2_var.get() == "mg": result.set(entryvar.get()*1000000000)
    elif cbox1_var.get() == "t" and cbox2_var.get() == "g": result.set(entryvar.get()*1000000)
    elif cbox1_var.get() == "t" and cbox2_var.get() == "kg": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "t" and cbox2_var.get() == "t": result.set(entryvar.get())
    elif cbox1_var.get() == "t" and cbox2_var.get() == "oz": result.set(entryvar.get()*35270)
    elif cbox1_var.get() == "t" and cbox2_var.get() == "lb": result.set(entryvar.get()*2205)
    elif cbox1_var.get() == "oz" and cbox2_var.get() == "mg": result.set(entryvar.get()*28350)
    elif cbox1_var.get() == "oz" and cbox2_var.get() == "g": result.set(entryvar.get()*28.35)
    elif cbox1_var.get() == "oz" and cbox2_var.get() == "kg": result.set(entryvar.get()/35.274)
    elif cbox1_var.get() == "oz" and cbox2_var.get() == "t": result.set(entryvar.get()/35274)
    elif cbox1_var.get() == "oz" and cbox2_var.get() == "oz": result.set(entryvar.get())
    elif cbox1_var.get() == "oz" and cbox2_var.get() == "lb": result.set(entryvar.get()/16)
    elif cbox1_var.get() == "lb" and cbox2_var.get() == "mg": result.set(entryvar.get()*453600)
    elif cbox1_var.get() == "lb" and cbox2_var.get() == "g": result.set(entryvar.get()*453.6)
    elif cbox1_var.get() == "lb" and cbox2_var.get() == "kg": result.set(entryvar.get()/2.205)
    elif cbox1_var.get() == "lb" and cbox2_var.get() == "t": result.set(entryvar.get()/2205)
    elif cbox1_var.get() == "lb" and cbox2_var.get() == "oz": result.set(entryvar.get()*16)
    elif cbox1_var.get() == "lb" and cbox2_var.get() == "lb": result.set(entryvar.get())
    elif cbox1_var.get() == "°C" and cbox2_var.get() == "°C": result.set(entryvar.get())
    elif cbox1_var.get() == "°C" and cbox2_var.get() == "°F": result.set(entryvar.get()*9/5+32)
    elif cbox1_var.get() == "°C" and cbox2_var.get() == "K": result.set(entryvar.get()+273.15)
    elif cbox1_var.get() == "°F" and cbox2_var.get() == "°C": result.set((entryvar.get()-32)*5/9)
    elif cbox1_var.get() == "°F" and cbox2_var.get() == "°F": result.set(entryvar.get())
    elif cbox1_var.get() == "°F" and cbox2_var.get() == "K": result.set((entryvar.get()-32)*5/9+273.15)
    elif cbox1_var.get() == "K" and cbox2_var.get() == "°C": result.set(entryvar.get()-273.15)
    elif cbox1_var.get() == "K" and cbox2_var.get() == "°F": result.set((entryvar.get()-273.15)*9/5+32)
    elif cbox1_var.get() == "K" and cbox2_var.get() == "K": result.set(entryvar.get())
    elif cbox1_var.get() == "cal" and cbox2_var.get() == "cal": result.set(entryvar.get())
    elif cbox1_var.get() == "cal" and cbox2_var.get() == "kcal": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "cal" and cbox2_var.get() == "J": result.set(entryvar.get()*4.184)
    elif cbox1_var.get() == "cal" and cbox2_var.get() == "kWh": result.set(entryvar.get()/860400)
    elif cbox1_var.get() == "kcal" and cbox2_var.get() == "cal": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "kcal" and cbox2_var.get() == "kcal": result.set(entryvar.get())
    elif cbox1_var.get() == "kcal" and cbox2_var.get() == "J": result.set(entryvar.get()*4184)
    elif cbox1_var.get() == "kcal" and cbox2_var.get() == "kWh": result.set(entryvar.get()/860.4)
    elif cbox1_var.get() == "J" and cbox2_var.get() == "cal": result.set(entryvar.get()/4.184)
    elif cbox1_var.get() == "J" and cbox2_var.get() == "kcal": result.set(entryvar.get()/4184)
    elif cbox1_var.get() == "J" and cbox2_var.get() == "J": result.set(entryvar.get())
    elif cbox1_var.get() == "J" and cbox2_var.get() == "kWh": result.set(entryvar.get()/3600000)
    elif cbox1_var.get() == "kWh" and cbox2_var.get() == "cal": result.set(entryvar.get()*860400)
    elif cbox1_var.get() == "kWh" and cbox2_var.get() == "kcal": result.set(entryvar.get()*860.4)
    elif cbox1_var.get() == "kWh" and cbox2_var.get() == "J": result.set(entryvar.get()*3600000)
    elif cbox1_var.get() == "kWh" and cbox2_var.get() == "kWh": result.set(entryvar.get())
    elif cbox1_var.get() == "W" and cbox2_var.get() == "W": result.set(entryvar.get())
    elif cbox1_var.get() == "W" and cbox2_var.get() == "kW": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "W" and cbox2_var.get() == "hp": result.set(entryvar.get()/745.7)
    elif cbox1_var.get() == "kW" and cbox2_var.get() == "W": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "kW" and cbox2_var.get() == "kW": result.set(entryvar.get())
    elif cbox1_var.get() == "kW" and cbox2_var.get() == "hp": result.set(entryvar.get()*1.341)
    elif cbox1_var.get() == "hp" and cbox2_var.get() == "W": result.set(entryvar.get()*745.7)
    elif cbox1_var.get() == "hp" and cbox2_var.get() == "kW": result.set(entryvar.get()/1.341)
    elif cbox1_var.get() == "hp" and cbox2_var.get() == "hp": result.set(entryvar.get())
    elif cbox1_var.get() == "Pa" and cbox2_var.get() == "Pa": result.set(entryvar.get())
    elif cbox1_var.get() == "Pa" and cbox2_var.get() == "atm": result.set(entryvar.get()/101300)
    elif cbox1_var.get() == "Pa" and cbox2_var.get() == "bar": result.set(entryvar.get()/100000)
    elif cbox1_var.get() == "Pa" and cbox2_var.get() == "Torr": result.set(entryvar.get()/133.3)
    elif cbox1_var.get() == "Pa" and cbox2_var.get() == "lbf/in²": result.set(entryvar.get()/6895)
    elif cbox1_var.get() == "atm" and cbox2_var.get() == "Pa": result.set(entryvar.get()*101300)
    elif cbox1_var.get() == "atm" and cbox2_var.get() == "atm": result.set(entryvar.get())
    elif cbox1_var.get() == "atm" and cbox2_var.get() == "bar": result.set(entryvar.get()*1.013)
    elif cbox1_var.get() == "atm" and cbox2_var.get() == "Torr": result.set(entryvar.get()*760)
    elif cbox1_var.get() == "atm" and cbox2_var.get() == "lbf/in²": result.set(entryvar.get()*14.696)
    elif cbox1_var.get() == "bar" and cbox2_var.get() == "Pa": result.set(entryvar.get()*100000)
    elif cbox1_var.get() == "bar" and cbox2_var.get() == "atm": result.set(entryvar.get()/1.013)
    elif cbox1_var.get() == "bar" and cbox2_var.get() == "bar": result.set(entryvar.get())
    elif cbox1_var.get() == "bar" and cbox2_var.get() == "Torr": result.set(entryvar.get()*750.1)
    elif cbox1_var.get() == "bar" and cbox2_var.get() == "lbf/in²": result.set(entryvar.get()*14.504)
    elif cbox1_var.get() == "Torr" and cbox2_var.get() == "Pa": result.set(entryvar.get()*133.3)
    elif cbox1_var.get() == "Torr" and cbox2_var.get() == "atm": result.set(entryvar.get()/760)
    elif cbox1_var.get() == "Torr" and cbox2_var.get() == "bar": result.set(entryvar.get()/750.1)
    elif cbox1_var.get() == "Torr" and cbox2_var.get() == "Torr": result.set(entryvar.get())
    elif cbox1_var.get() == "Torr" and cbox2_var.get() == "lbf/in²": result.set(entryvar.get()/51.715)
    elif cbox1_var.get() == "lbf/in²" and cbox2_var.get() == "Pa": result.set(entryvar.get()*6895)
    elif cbox1_var.get() == "lbf/in²" and cbox2_var.get() == "atm": result.set(entryvar.get()/14.696)
    elif cbox1_var.get() == "lbf/in²" and cbox2_var.get() == "bar": result.set(entryvar.get()/14.504)
    elif cbox1_var.get() == "lbf/in²" and cbox2_var.get() == "Torr": result.set(entryvar.get()*51.715)
    elif cbox1_var.get() == "lbf/in²" and cbox2_var.get() == "lbf/in²": result.set(entryvar.get())
    elif cbox1_var.get() == "b" and cbox2_var.get() == "b": result.set(entryvar.get())
    elif cbox1_var.get() == "b" and cbox2_var.get() == "B": result.set(entryvar.get()/8)
    elif cbox1_var.get() == "b" and cbox2_var.get() == "Kb": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "b" and cbox2_var.get() == "KB": result.set(entryvar.get()/8000)
    elif cbox1_var.get() == "b" and cbox2_var.get() == "Mb": result.set(entryvar.get()/1000000)
    elif cbox1_var.get() == "b" and cbox2_var.get() == "MB": result.set(entryvar.get()/8000000)
    elif cbox1_var.get() == "b" and cbox2_var.get() == "Gb": result.set(entryvar.get()/1000000000)
    elif cbox1_var.get() == "b" and cbox2_var.get() == "GB": result.set(entryvar.get()/8000000000)
    elif cbox1_var.get() == "b" and cbox2_var.get() == "Tb": result.set(entryvar.get()/1000000000000)
    elif cbox1_var.get() == "b" and cbox2_var.get() == "TB": result.set(entryvar.get()/8000000000000)
    elif cbox1_var.get() == "B" and cbox2_var.get() == "b": result.set(entryvar.get()*8)
    elif cbox1_var.get() == "B" and cbox2_var.get() == "B": result.set(entryvar.get())
    elif cbox1_var.get() == "B" and cbox2_var.get() == "Kb": result.set(entryvar.get()/125)
    elif cbox1_var.get() == "B" and cbox2_var.get() == "KB": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "B" and cbox2_var.get() == "Mb": result.set(entryvar.get()/125000)
    elif cbox1_var.get() == "B" and cbox2_var.get() == "MB": result.set(entryvar.get()/1000000)
    elif cbox1_var.get() == "B" and cbox2_var.get() == "Gb": result.set(entryvar.get()/125000000)
    elif cbox1_var.get() == "B" and cbox2_var.get() == "GB": result.set(entryvar.get()/1000000000)
    elif cbox1_var.get() == "B" and cbox2_var.get() == "Tb": result.set(entryvar.get()/125000000000)
    elif cbox1_var.get() == "B" and cbox2_var.get() == "TB": result.set(entryvar.get()/1000000000000)
    elif cbox1_var.get() == "Kb" and cbox2_var.get() == "b": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "Kb" and cbox2_var.get() == "B": result.set(entryvar.get()*125)
    elif cbox1_var.get() == "Kb" and cbox2_var.get() == "Kb": result.set(entryvar.get())
    elif cbox1_var.get() == "Kb" and cbox2_var.get() == "KB": result.set(entryvar.get()/8)
    elif cbox1_var.get() == "Kb" and cbox2_var.get() == "Mb": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "Kb" and cbox2_var.get() == "MB": result.set(entryvar.get()/8000)
    elif cbox1_var.get() == "Kb" and cbox2_var.get() == "Gb": result.set(entryvar.get()/1000000)
    elif cbox1_var.get() == "Kb" and cbox2_var.get() == "GB": result.set(entryvar.get()/8000000)
    elif cbox1_var.get() == "Kb" and cbox2_var.get() == "Tb": result.set(entryvar.get()/1000000000)
    elif cbox1_var.get() == "Kb" and cbox2_var.get() == "TB": result.set(entryvar.get()/8000000000)
    elif cbox1_var.get() == "KB" and cbox2_var.get() == "b": result.set(entryvar.get()*8000)
    elif cbox1_var.get() == "KB" and cbox2_var.get() == "B": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "KB" and cbox2_var.get() == "Kb": result.set(entryvar.get()*8)
    elif cbox1_var.get() == "KB" and cbox2_var.get() == "KB": result.set(entryvar.get())
    elif cbox1_var.get() == "KB" and cbox2_var.get() == "Mb": result.set(entryvar.get()/125)
    elif cbox1_var.get() == "KB" and cbox2_var.get() == "MB": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "KB" and cbox2_var.get() == "Gb": result.set(entryvar.get()/125000)
    elif cbox1_var.get() == "KB" and cbox2_var.get() == "GB": result.set(entryvar.get()/1000000)
    elif cbox1_var.get() == "KB" and cbox2_var.get() == "Tb": result.set(entryvar.get()/125000000)
    elif cbox1_var.get() == "KB" and cbox2_var.get() == "TB": result.set(entryvar.get()/1000000000)
    elif cbox1_var.get() == "Mb" and cbox2_var.get() == "b": result.set(entryvar.get()*1000000)
    elif cbox1_var.get() == "Mb" and cbox2_var.get() == "B": result.set(entryvar.get()*125000)
    elif cbox1_var.get() == "Mb" and cbox2_var.get() == "Kb": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "Mb" and cbox2_var.get() == "KB": result.set(entryvar.get()*125)
    elif cbox1_var.get() == "Mb" and cbox2_var.get() == "Mb": result.set(entryvar.get())
    elif cbox1_var.get() == "Mb" and cbox2_var.get() == "MB": result.set(entryvar.get()/8)
    elif cbox1_var.get() == "Mb" and cbox2_var.get() == "Gb": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "Mb" and cbox2_var.get() == "GB": result.set(entryvar.get()/8000)
    elif cbox1_var.get() == "Mb" and cbox2_var.get() == "Tb": result.set(entryvar.get()/1000000)
    elif cbox1_var.get() == "Mb" and cbox2_var.get() == "TB": result.set(entryvar.get()/8000000)
    elif cbox1_var.get() == "MB" and cbox2_var.get() == "b": result.set(entryvar.get()*8000000)
    elif cbox1_var.get() == "MB" and cbox2_var.get() == "B": result.set(entryvar.get()*1000000)
    elif cbox1_var.get() == "MB" and cbox2_var.get() == "Kb": result.set(entryvar.get()*8000)
    elif cbox1_var.get() == "MB" and cbox2_var.get() == "KB": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "MB" and cbox2_var.get() == "Mb": result.set(entryvar.get()*8)
    elif cbox1_var.get() == "MB" and cbox2_var.get() == "MB": result.set(entryvar.get())
    elif cbox1_var.get() == "MB" and cbox2_var.get() == "Gb": result.set(entryvar.get()/125)
    elif cbox1_var.get() == "MB" and cbox2_var.get() == "GB": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "MB" and cbox2_var.get() == "Tb": result.set(entryvar.get()/125000)
    elif cbox1_var.get() == "MB" and cbox2_var.get() == "TB": result.set(entryvar.get()/1000000)
    elif cbox1_var.get() == "Gb" and cbox2_var.get() == "b": result.set(entryvar.get()*1000000000)
    elif cbox1_var.get() == "Gb" and cbox2_var.get() == "B": result.set(entryvar.get()*125000000)
    elif cbox1_var.get() == "Gb" and cbox2_var.get() == "Kb": result.set(entryvar.get()*1000000)
    elif cbox1_var.get() == "Gb" and cbox2_var.get() == "KB": result.set(entryvar.get()*125000)
    elif cbox1_var.get() == "Gb" and cbox2_var.get() == "Mb": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "Gb" and cbox2_var.get() == "MB": result.set(entryvar.get()*125)
    elif cbox1_var.get() == "Gb" and cbox2_var.get() == "Gb": result.set(entryvar.get())
    elif cbox1_var.get() == "Gb" and cbox2_var.get() == "GB": result.set(entryvar.get()/8)
    elif cbox1_var.get() == "Gb" and cbox2_var.get() == "Tb": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "Gb" and cbox2_var.get() == "TB": result.set(entryvar.get()/8000)
    elif cbox1_var.get() == "GB" and cbox2_var.get() == "b": result.set(entryvar.get()*8000000000)
    elif cbox1_var.get() == "GB" and cbox2_var.get() == "B": result.set(entryvar.get()*1000000000)
    elif cbox1_var.get() == "GB" and cbox2_var.get() == "Kb": result.set(entryvar.get()*8000000)
    elif cbox1_var.get() == "GB" and cbox2_var.get() == "KB": result.set(entryvar.get()*1000000)
    elif cbox1_var.get() == "GB" and cbox2_var.get() == "Mb": result.set(entryvar.get()*8000)
    elif cbox1_var.get() == "GB" and cbox2_var.get() == "MB": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "GB" and cbox2_var.get() == "Gb": result.set(entryvar.get()*8)
    elif cbox1_var.get() == "GB" and cbox2_var.get() == "GB": result.set(entryvar.get())
    elif cbox1_var.get() == "GB" and cbox2_var.get() == "Tb": result.set(entryvar.get()/8)
    elif cbox1_var.get() == "GB" and cbox2_var.get() == "TB": result.set(entryvar.get()/1000)
    elif cbox1_var.get() == "Tb" and cbox2_var.get() == "b": result.set(entryvar.get()*1000000000000)
    elif cbox1_var.get() == "Tb" and cbox2_var.get() == "B": result.set(entryvar.get()*125000000000)
    elif cbox1_var.get() == "Tb" and cbox2_var.get() == "Kb": result.set(entryvar.get()*1000000000)
    elif cbox1_var.get() == "Tb" and cbox2_var.get() == "KB": result.set(entryvar.get()*125000000)
    elif cbox1_var.get() == "Tb" and cbox2_var.get() == "Mb": result.set(entryvar.get()*1000000)
    elif cbox1_var.get() == "Tb" and cbox2_var.get() == "MB": result.set(entryvar.get()*125000)
    elif cbox1_var.get() == "Tb" and cbox2_var.get() == "Gb": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "Tb" and cbox2_var.get() == "GB": result.set(entryvar.get()*125)
    elif cbox1_var.get() == "Tb" and cbox2_var.get() == "Tb": result.set(entryvar.get())
    elif cbox1_var.get() == "Tb" and cbox2_var.get() == "TB": result.set(entryvar.get()/8)
    elif cbox1_var.get() == "TB" and cbox2_var.get() == "b": result.set(entryvar.get()*8000000000000)
    elif cbox1_var.get() == "TB" and cbox2_var.get() == "B": result.set(entryvar.get()*1000000000000)
    elif cbox1_var.get() == "TB" and cbox2_var.get() == "Kb": result.set(entryvar.get()*8000000000)
    elif cbox1_var.get() == "TB" and cbox2_var.get() == "KB": result.set(entryvar.get()*1000000000)
    elif cbox1_var.get() == "TB" and cbox2_var.get() == "Mb": result.set(entryvar.get()*8000000)
    elif cbox1_var.get() == "TB" and cbox2_var.get() == "MB": result.set(entryvar.get()*1000000)
    elif cbox1_var.get() == "TB" and cbox2_var.get() == "Gb": result.set(entryvar.get()*8000)
    elif cbox1_var.get() == "TB" and cbox2_var.get() == "GB": result.set(entryvar.get()*1000)
    elif cbox1_var.get() == "TB" and cbox2_var.get() == "Tb": result.set(entryvar.get()*8)
    elif cbox1_var.get() == "TB" and cbox2_var.get() == "TB": result.set(entryvar.get())
    elif cbox1_var.get() == "deg" and cbox2_var.get() == "deg": result.set(entryvar.get())
    elif cbox1_var.get() == "deg" and cbox2_var.get() == "rad": result.set(entryvar.get()*pi/180)
    elif cbox1_var.get() == "deg" and cbox2_var.get() == "grad": result.set(entryvar.get()*10/9)
    elif cbox1_var.get() == "rad" and cbox2_var.get() == "deg": result.set(entryvar.get()*180/pi)
    elif cbox1_var.get() == "rad" and cbox2_var.get() == "rad": result.set(entryvar.get())
    elif cbox1_var.get() == "rad" and cbox2_var.get() == "grad": result.set(entryvar.get()*200/pi)
    elif cbox1_var.get() == "grad" and cbox2_var.get() == "deg": result.set(entryvar.get()*9/10)
    elif cbox1_var.get() == "grad" and cbox2_var.get() == "rad": result.set(entryvar.get()*pi/200)
    elif cbox1_var.get() == "grad" and cbox2_var.get() == "grad": result.set(entryvar.get())
    else: showerror(title="Error", message="Please select unit(s) from the list(s).")

def reset(x):
    cbox1_var.set("")
    cbox2_var.set("")
    entryvar.set(0.0)
    result.set(0.0)

root = tk.Tk()
root.geometry("530x160+50+50")
root.resizable(False, False)
root.title("Unit Converter")

notebook = ttk.Notebook(root)
notebook.bind("<<NotebookTabChanged>>", reset)
notebook.pack()

length = ttk.Frame(notebook, width=480, height=160)
length.pack()
area = ttk.Frame(notebook)
area.pack()
volume = ttk.Frame(notebook)
volume.pack()
time = ttk.Frame(notebook)
time.pack()
speed = ttk.Frame(notebook)
speed.pack()
mass = ttk.Frame(notebook)
mass.pack()
temperature = ttk.Frame(notebook)
temperature.pack()
energy = ttk.Frame(notebook)
energy.pack()
power = ttk.Frame(notebook)
power.pack()
pressure = ttk.Frame(notebook)
pressure.pack()
data = ttk.Frame(notebook)
data.pack()
angle = ttk.Frame(notebook)
angle.pack()

notebook.add(length, text="Length")
notebook.add(area, text="Area")
notebook.add(volume, text="Volume")
notebook.add(time, text="Time")
notebook.add(speed, text="Speed")
notebook.add(mass, text="Mass")
notebook.add(temperature, text="Temperature")
notebook.add(energy, text="Energy")
notebook.add(power, text="Power")
notebook.add(pressure, text="Pressure")
notebook.add(data, text="Data")
notebook.add(angle, text="Angle")

quantities = [length, area, volume, time, speed, mass, temperature, energy, power, pressure, data, angle]
units_length = ["mm", "cm", "m", "km", "in", "ft", "mi", "ly"]
units_area = ["cm²", "m²", "km²", "are", "decare", "hectare", "sq in", "sq ft", "acre"]
units_volume = ["cm³", "dm³", "m³", "mL", "cL", "L", "cu in", "cu ft"]
units_time = ["s", "min", "h", "d", "wk", "mo", "yr"]
units_speed = ["km/h", "m/s", "mph", "kn", "ft/s"]
units_mass = ["mg", "g", "kg", "t", "oz", "lb"]
units_temperature = ["°C", "°F", "K"]
units_energy = ["cal", "kcal", "J", "kWh"]
units_power = ["W", "kW", "hp"]
units_pressure = ["Pa", "atm", "bar", "Torr", "lbf/in²"]
units_data = ["b", "B", "Kb", "KB", "Mb", "MB", "Gb", "GB", "Tb", "TB"]
units_angle = ["deg", "rad", "grad"]
dict_quantities = {length: units_length, area: units_area, volume: units_volume, time: units_time, speed: units_speed, mass: units_mass, temperature: units_temperature, energy: units_energy, power: units_power, pressure: units_pressure, data: units_data, angle: units_angle}

entryvar = tk.DoubleVar()
entryvar.set(0.0)
cbox1_var = tk.StringVar()
cbox2_var = tk.StringVar()
result = tk.DoubleVar()
result.set(0.0)

for quantity in quantities:
    lbl1_style = ttk.Style()
    lbl1_style.configure("Label1.TLabel", font=("TkDefaultFont", 14))
    lbl1 = ttk.Label(quantity, text="From:", style="Label1.TLabel")
    lbl1.place(x=5, y=12)
    
    ntry = ttk.Entry(quantity, textvariable=entryvar)
    ntry.place(x=70, y=10, width=180, height=30)
    
    units1 = ttk.Combobox(quantity, state="readonly", textvariable=cbox1_var, values=[""]+dict_quantities[quantity])
    units1.place(x=255, y=10, width=70, height=30)

    lbl2 = ttk.Label(quantity, text="To:", style="Label1.TLabel")
    lbl2.place(x=5, y=50)
    
    units2 = ttk.Combobox(quantity, state="readonly", textvariable=cbox2_var, values=[""]+dict_quantities[quantity])
    units2.place(x=70, y=50, width=180, height=30)
    
    lbl3 = ttk.Label(quantity, textvariable=result, style="Label1.TLabel")
    lbl3.place(x=80, y=90)

    bttn = ttk.Button(quantity, text="Convert", command=lambda: convert(0))
    bttn.place(x=254, y=49, width=72, height=32)

    lbl3 = ttk.Label(quantity, text="Result:", style="Label1.TLabel")
    lbl3.place(x=5, y=90)
        
    lbl4_style = ttk.Style()
    lbl4_style.configure("Label2.TLabel", font=("Vivaldi", 18))
    lbl4 = ttk.Label(quantity, text="by Batuhan Akçan", style="Label2.TLabel", foreground="red")
    lbl4.place(x=350, y=100)

root.bind("<KeyPress-Return>", convert)
root.mainloop()
